# Site settings
title: Papers-Notes
tag_text: Papers-Notes
description: Small mini blog sized notes, or note sized blogs.

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
